---
- name: install docker host for ubuntu
  hosts: '{{ hosts }}'
  sudo: true
  tasks:
    - name: Add docker repo
      shell: apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - name: Fix the proxy error
      shell: echo 'Acquire::HTTP::Proxy::apt.dockerproject.org "DIRECT";' >> /etc/apt/apt.conf
    - name: Add docker source list
      shell: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list
    - name: Install docker host
      apt: name=docker-engine update_cache=yes
    - name: add ubuntu user to the docker group
      shell: usermod -aG docker ubuntu
